### PR TITLE
Add 'relativeReference', a quasiquoter for relative references

### PR DESCRIPTION
**Pull request by neongreen**
Also in this PR:

* A changelog
* Fixed doctests for newer GHCs
* Bumped GHC version on Travis

### CODE REVIEW

**Comment by snakamura** [comment]
Thank you for the PR and sorry for the delay. I've not noticed this MR since my email client sent the notification to somewhere.

I have three questions and requests.

- I've merged another MR (#5) to upgrade GHC to 8.4 on travis, so please rebase this branch on master
- I'm not sure I need to upgrade doctest to 0.14. Are there any specific reasons to bump the version? I'd like to move it to another MR if we need to do so.
- It's a bit inconsistent to call them `staticRelativeRef` and `relativeRef` that call `parseRelativeReference`. How about calling them `staticRelativeReference` and `relativeReference`?

**Comment by neongreen** [comment]
I think there was a reason for doctest-0.14, but I'm not sure. I'll check.

As for the naming – I think it's more consistent with the rest of the ecosystem, but surely I will change it if you want. My opinion is based on:

* RFC 3986 uses `relative-ref` in the grammar description: https://tools.ietf.org/html/rfc3986#appendix-A
* The `uri-bytestring` package uses `relativeRef`
* The `hweblib` package uses `relativeRef`

**Comment by neongreen** [comment]
NB: if you are interested in doing #4, it might also be nice to ask the opinion of `network-uri` maintainers. @ezrakilty do you have any thoughts on the naming here?

**Comment by ezrakilty** [comment]
Well, naming is always hard. `network-uri` has used `parseRelativeReference` for a long time (before I even took maintainership). `network-uri-static` is of course more closely aligned with `network-uri` than with those other packages, so it seems like it would be better to keep the names consistent within this tiny universe.

**Comment by snakamura** [comment]
@ezrakilty Thank you. I agree with that. @neongreen Can you rename them?

**Comment by neongreen** [comment]
@snakamura Rebased, renamed `relativeRef`, and removed the doctest bump.

**Comment by snakamura** [comment]
Thank you. Merged and published 0.1.1.0 to hackage.

**Comment by snakamura** [comment]
Thank you. Merged and published 0.1.1.0 to hackage.

**Comment by snakamura** [comment]
Thank you. Merged and released to hackage.

**Pull request merged**
