### PR TITLE
Expose nothing with network-uri 2.7.0 and later

### PR DESCRIPTION
**Pull request by snakamura**
This change should have been included in #6.

### CODE REVIEW

**Comment by snakamura** [comment]
@neongreen Which version of GHC do you use? It seems it compiles with GHC 8.4.4. https://travis-ci.org/snakamura/network-uri-static/builds/456873926

**Comment by snakamura** [comment]
@neongreen Oh, you should have meant you complied it with network-uri-2.7.0. I'll check it.

**Comment by ezrakilty** [comment]
@snakamura I think you need to provide an empty module definition in `#if` branch that is currently completely empty. With no definition at all, the module name defaults to `Main`, which doesn't match the filename :-/

So, I think you need something like this:

```
#if MIN_VERSION_network_uri(2,7,0)
module Network.URI.Static () where
#else
-- <The whole of the module, including the module ... where header>
#endif
```

**Comment by ezrakilty** [comment]
Please have a look #8 which tries to address this issue.

**Comment by snakamura** [comment]
Closing in favor of #8.

**Pull request closed without merging**
