### PR TITLE
Fix the version number of network-uri at which the consolidation took place

### PR DESCRIPTION
**Pull request by ezrakilty**
I screwed up the attempt to merge this into network-uri in that I released it as 2.7 even though no breaking changes had occurred, so I then scrubbed that release number and released the consolidation of the two packages at network-uri-2.6.3. This fixes the corresponding change in network-uri-static so that it correctly becomes silent if you have network-uri-2.6.3 or later.

(This pull request actually seems to include some material that was already merged into network-uri-static, so maybe I'm not creating the pull request correctly. Does it cause any merging pain on your side, @snakamura?)

### CODE REVIEW

**Comment by snakamura** [comment]
@ezrakilty Thank you. Can you rebase this PR on master? As you said, this PR contains lots of stuff that have already been merged in #8 .

**Comment by ezrakilty** [comment]
OK, I'm a little puzzled by git, but I think I've resolved all these conflicts. @snakamura, can you let me know if this is good?

**Comment by snakamura** [comment]
@ezrakilty Thank you! I found one typo, but I'll squash the commits and merge this branch once you've fixed it.

Just for your information, it'd be nice if you reset your master to this repo and create a PR from a topic-branch usually.

```
# Add this repository to your repo and fetch
git remote add base git@github.com:snakamura/network-uri-static.git
git fetch base

# Check out master and reset it to the base/master
git checkout master
git reset base/master

# Create a topic branch
git checkout -b fix_something

# Make changes and commit
git commit -a

# Push it
git push -u

# Create a PR from fix_something branch
```

This will create cleaner commit history.

**Comment by snakamura** [comment]
Opened #10 and merged it.

**Comment by snakamura** [comment]
@ezrakilty Released 0.1.2.2 after merging #10 and #11. Let me know if you find any problems. Thank you for your help.

**Comment by ezrakilty** [comment]
Oh, thank you for taking care of it, and for the tip about using a topic branch. Didn't realize I could do that on someone else's repo!

**Pull request closed without merging**
